-- MySQL Script generated by MySQL Workbench
-- Wed Dec 29 16:16:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tashpmi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tashpmi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tashpmi` DEFAULT CHARACTER SET utf8 ;
USE `tashpmi` ;

-- -----------------------------------------------------
-- Table `tashpmi`.`institut_structura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`institut_structura` (
  `facultet_nomi` VARCHAR(200) NOT NULL,
  `bo'lim_nomi` VARCHAR(150) NOT NULL,
  `administratsiya` VARCHAR(45) NOT NULL,
  `qo'shimcha` VARCHAR(45) NULL,
  PRIMARY KEY (`facultet_nomi`, `bo'lim_nomi`, `administratsiya`),
  UNIQUE INDEX `faculty_name_UNIQUE` (`facultet_nomi` ASC) VISIBLE,
  UNIQUE INDEX `bo'lim_nomi_UNIQUE` (`bo'lim_nomi` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`1- ped_faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`1- ped_faculty` (
  `departments_name` VARCHAR(300) NOT NULL,
  `students_id` VARCHAR(45) NOT NULL,
  `students_firstname` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `faculty_name` VARCHAR(200) NOT NULL,
  `kurs` INT NOT NULL,
  `guruh` INT NOT NULL,
  PRIMARY KEY (`departments_name`, `students_id`, `students_firstname`, `students_lastname`, `kurs`, `guruh`),
  UNIQUE INDEX `departments_UNIQUE` (`departments_name` ASC) VISIBLE,
  UNIQUE INDEX `students_id_UNIQUE` (`students_id` ASC) VISIBLE,
  INDEX `facname1_idx` (`faculty_name` ASC) VISIBLE,
  CONSTRAINT `facname1`
    FOREIGN KEY (`faculty_name`)
    REFERENCES `tashpmi`.`institut_structura` (`facultet_nomi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`2-ped_faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`2-ped_faculty` (
  `department_name` VARCHAR(300) NOT NULL,
  `student_id` VARCHAR(45) NOT NULL,
  `students_firstname` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `faculty_name` VARCHAR(200) NOT NULL,
  `kurs` INT NOT NULL,
  `guruh` INT NOT NULL,
  PRIMARY KEY (`department_name`, `student_id`, `students_firstname`, `students_lastname`, `kurs`, `guruh`),
  UNIQUE INDEX `department_name_UNIQUE` (`department_name` ASC) VISIBLE,
  UNIQUE INDEX `student_id_UNIQUE` (`student_id` ASC) VISIBLE,
  INDEX `facname2_idx` (`faculty_name` ASC) VISIBLE,
  CONSTRAINT `facname2`
    FOREIGN KEY (`faculty_name`)
    REFERENCES `tashpmi`.`institut_structura` (`facultet_nomi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`med_ped`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`med_ped` (
  `departments_name` VARCHAR(300) NOT NULL,
  `students_id` VARCHAR(45) NOT NULL,
  `students_firstname` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `faculty_name` VARCHAR(200) NOT NULL,
  `kurs` INT NOT NULL,
  `guruh` INT NOT NULL,
  PRIMARY KEY (`departments_name`, `students_id`, `students_firstname`, `students_lastname`, `kurs`, `guruh`),
  UNIQUE INDEX `departments_name_UNIQUE` (`departments_name` ASC) VISIBLE,
  UNIQUE INDEX `students_id_UNIQUE` (`students_id` ASC) VISIBLE,
  INDEX `facnamemp_idx` (`faculty_name` ASC) VISIBLE,
  CONSTRAINT `facnamemp`
    FOREIGN KEY (`faculty_name`)
    REFERENCES `tashpmi`.`institut_structura` (`facultet_nomi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`xalqaro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`xalqaro` (
  `students_id` VARCHAR(45) NOT NULL,
  `students_firstnmae` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `faculty_name` VARCHAR(45) NULL,
  `kurs` INT NOT NULL,
  `guruh` INT NOT NULL,
  PRIMARY KEY (`students_id`, `students_firstnmae`, `students_lastname`, `kurs`, `guruh`),
  UNIQUE INDEX `students_id_UNIQUE` (`students_id` ASC) VISIBLE,
  INDEX `facnamexal_idx` (`faculty_name` ASC) VISIBLE,
  CONSTRAINT `facnamexal`
    FOREIGN KEY (`faculty_name`)
    REFERENCES `tashpmi`.`institut_structura` (`facultet_nomi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`xamshira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`xamshira` (
  `students_id` VARCHAR(45) NOT NULL,
  `students_firstname` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `faculty_namel` VARCHAR(200) NOT NULL,
  `kurs` INT NOT NULL,
  `guruh` INT NOT NULL,
  PRIMARY KEY (`students_id`, `students_firstname`, `students_lastname`, `kurs`, `guruh`),
  UNIQUE INDEX `students_id_UNIQUE` (`students_id` ASC) VISIBLE,
  INDEX `facnamex_idx` (`faculty_namel` ASC) VISIBLE,
  CONSTRAINT `facnamex`
    FOREIGN KEY (`faculty_namel`)
    REFERENCES `tashpmi`.`institut_structura` (`facultet_nomi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`yotoqxona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`yotoqxona` (
  `students_id` VARCHAR(45) NOT NULL,
  `students_firstname` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `xodim_first_name` VARCHAR(45) NOT NULL,
  `xodim_last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`students_id`),
  UNIQUE INDEX `students_id_UNIQUE` (`students_id` ASC) VISIBLE,
  INDEX `st_f_name_idx` (`students_firstname` ASC) VISIBLE,
  INDEX `st_l_name1_idx` (`students_lastname` ASC) VISIBLE,
  CONSTRAINT `student1`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student2`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_xal`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`xalqaro` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_mp`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`med_ped` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_x`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`xamshira` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_f_name1`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_f_name2`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_f_name_mp`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`med_ped` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_f_name_xal`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`xalqaro` (`students_firstnmae`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_f_name_x`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`xamshira` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_l_name1`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_l_name2`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_l_n_mp`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`med_ped` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_l_n_xal`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`xalqaro` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `st_l_n_x`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`xamshira` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_1_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_1_1` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_1_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_1_2` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname0`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_1_3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_1_3` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname00`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_1_4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_1_4` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname01`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_2_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_2_1` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`department_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_2_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_2_2` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname1`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`department_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_2_3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_2_3` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname10`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`department_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_2_4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_2_4` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname100`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`department_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_3_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_3_1` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname3_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname3`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`med_ped` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_3_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_3_2` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname3_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname30`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`med_ped` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_3_3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_3_3` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname3_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname300`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`med_ped` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`department_3_4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`department_3_4` (
  `department_name` VARCHAR(300) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `pps_m_name` VARCHAR(45) NULL,
  `pps_birth_date` DATE NOT NULL,
  `pps_enter_date` DATE NOT NULL,
  `pps_age` INT NOT NULL,
  `pps_titul` VARCHAR(45) NOT NULL,
  `pps_respons` VARCHAR(45) NULL,
  INDEX `depname3_idx` (`department_name` ASC) VISIBLE,
  PRIMARY KEY (`pps_name`, `pps_surname`),
  CONSTRAINT `depname3000`
    FOREIGN KEY (`department_name`)
    REFERENCES `tashpmi`.`med_ped` (`departments_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`pps_oylik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`pps_oylik` (
  `id_pps` VARCHAR(50) NOT NULL,
  `pps_name` VARCHAR(45) NOT NULL,
  `pps_surname` VARCHAR(45) NOT NULL,
  `ish_yuklama_stavka` DECIMAL NOT NULL,
  `oylik_maosh` INT NOT NULL,
  `ishlangan_kun` INT NOT NULL,
  `qqs` INT NOT NULL,
  `summa` INT NOT NULL,
  `plastik_karta_raqami` VARCHAR(45) NOT NULL,
  `hisob_raqami` VARCHAR(45) NOT NULL,
  `pasport_seriya` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pps`),
  UNIQUE INDEX `id_pps_UNIQUE` (`id_pps` ASC) VISIBLE,
  INDEX `name_idx` (`pps_name` ASC) VISIBLE,
  INDEX `sn_idx` (`pps_surname` ASC) VISIBLE,
  UNIQUE INDEX `plastik_karta_raqami_UNIQUE` (`plastik_karta_raqami` ASC) VISIBLE,
  UNIQUE INDEX `hisob_raqami_UNIQUE` (`hisob_raqami` ASC) VISIBLE,
  UNIQUE INDEX `pasport_seriya_UNIQUE` (`pasport_seriya` ASC) VISIBLE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_1_1` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_1_2` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_1_3` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_1_4` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_2_1` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_2_2` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_2_3` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_2_4` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_3_1` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_3_2` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_3_3` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`pps_name`)
    REFERENCES `tashpmi`.`department_3_4` (`pps_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_1_1` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_1_2` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_1_3` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_1_4` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_2_1` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_2_2` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_2_3` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_2_4` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_3_1` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_3_2` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_3_3` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sn`
    FOREIGN KEY (`pps_surname`)
    REFERENCES `tashpmi`.`department_3_4` (`pps_surname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`talaba_stipendiya`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`talaba_stipendiya` (
  `students_id` VARCHAR(45) NOT NULL,
  `students_firstname` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `kurs` INT NOT NULL,
  `guruh` INT NOT NULL,
  `hisob_raqami` VARCHAR(45) NOT NULL,
  `plastik_karta_raqami` VARCHAR(45) NOT NULL,
  `oylik_stipendita` INT NOT NULL,
  `pasport_seriya` VARCHAR(45) NOT NULL,
  INDEX `stid_idx` (`students_id` ASC) VISIBLE,
  INDEX `name_idx` (`students_firstname` ASC) VISIBLE,
  INDEX `ln_idx` (`students_lastname` ASC) VISIBLE,
  INDEX `k_idx` (`kurs` ASC) VISIBLE,
  INDEX `g_idx` (`guruh` ASC) VISIBLE,
  PRIMARY KEY (`pasport_seriya`),
  CONSTRAINT `stid`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`med_ped` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`xalqaro` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`xamshira` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`med_ped` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`xalqaro` (`students_firstnmae`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`xamshira` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`med_ped` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`xalqaro` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`xamshira` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`med_ped` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`xalqaro` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`xamshira` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`med_ped` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`xalqaro` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`xamshira` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tashpmi`.`talaba_kontrakt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tashpmi`.`talaba_kontrakt` (
  `students_id` VARCHAR(45) NOT NULL,
  `students_firstname` VARCHAR(45) NOT NULL,
  `students_lastname` VARCHAR(45) NOT NULL,
  `kurs` INT NOT NULL,
  `guruh` INT NOT NULL,
  `hisob_raqami` VARCHAR(45) NOT NULL,
  `plastik_karta_raqami` VARCHAR(45) NOT NULL,
  `yillik_kontrakt_miqdori` INT NOT NULL,
  `yar_yil_kon_miq` INT NOT NULL,
  `1_to'lov_muddati` DATE NOT NULL,
  `2-_to'lov_muddati` DATE NOT NULL,
  `joriy_o'quv_yili` VARCHAR(45) NOT NULL,
  `to'langan_summa` DECIMAL NOT NULL,
  `to'langan_sana` DATE NOT NULL,
  `pasport_seriya` VARCHAR(45) NOT NULL,
  INDEX `stid_idx` (`students_id` ASC) VISIBLE,
  INDEX `name_idx` (`students_firstname` ASC) VISIBLE,
  INDEX `ln_idx` (`students_lastname` ASC) VISIBLE,
  INDEX `k_idx` (`kurs` ASC) VISIBLE,
  INDEX `g_idx` (`guruh` ASC) VISIBLE,
  INDEX `pasport_idx` (`pasport_seriya` ASC) VISIBLE,
  CONSTRAINT `stid0`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid1`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid2`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`med_ped` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid3`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`xalqaro` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stid4`
    FOREIGN KEY (`students_id`)
    REFERENCES `tashpmi`.`xamshira` (`students_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name0`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name1`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name2`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`med_ped` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name3`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`xalqaro` (`students_firstnmae`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `name4`
    FOREIGN KEY (`students_firstname`)
    REFERENCES `tashpmi`.`xamshira` (`students_firstname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln0`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln1`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln2`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`med_ped` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln3`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`xalqaro` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ln4`
    FOREIGN KEY (`students_lastname`)
    REFERENCES `tashpmi`.`xamshira` (`students_lastname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k0`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k1`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k2`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`med_ped` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k3`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`xalqaro` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `k4`
    FOREIGN KEY (`kurs`)
    REFERENCES `tashpmi`.`xamshira` (`kurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g0`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`1- ped_faculty` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g1`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`2-ped_faculty` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g2`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`med_ped` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g3`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`xalqaro` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `g4`
    FOREIGN KEY (`guruh`)
    REFERENCES `tashpmi`.`xamshira` (`guruh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pasport`
    FOREIGN KEY (`pasport_seriya`)
    REFERENCES `tashpmi`.`talaba_stipendiya` (`pasport_seriya`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
